---
- name: Variables Playbook
  hosts: copenhagen

  vars:
    is_it_break_time: true

    color1: green
    color2: blue
    colors: "Show all the colors {{ color2 }} and {{ color1 }}"

    color_list:
      - yellow
      - magenta
      - cyan

    spaceshuttles:
      Columbia:
        First_flight: April 12 1981
        Total_flights: 28
      Challanger:
        First_flight: April 4 1983
        Total_flights: 10
      Discovery:
        First_flight: August 30 1984
        Total_flights: 39
      Atlantis:
        First_flight: 3 October 1985
        Total_flights: 33
      Endeavour:
        First_flight: May 7 1992
        Total_flights: 25

  tasks:
    - name: Show Color
      ansible.builtin.debug:
        msg: "{{ colors }}"

    - name: Show Color from list
      ansible.builtin.debug:
        msg: "{{ color_list[1] }}"

    - name: Atlantis Total flights
      ansible.builtin.debug:
        msg: "{{ spaceshuttles['Atlantis']['Total_flights'] }}"
    - name: Is it break time
      ansible.builtin.debug:
        msg: "{{ is_it_break_time }}"
